name: vosk_flutter_plugin
description: Flutter plugin for Vosk speech recognition model.
version: 1.0.2
homepage: https://alphacephei.com/
repository: https://github.com/alphacep/vosk-flutter

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  archive: ^3.1.8
  flutter:
    sdk: flutter
  http: ^0.13.5
  path: ^1.8.2
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1

flutter:
  plugin:
    platforms:
      android:
        package: org.vosk.vosk_flutter_plugin
        pluginClass: VoskFlutterPlugin
