name: vosk_flutter

on: [ push ]

jobs:
  unit_test:
    runs-on: macos-latest
    timeout-minutes: 5
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Configure scripts "
        run: chmod +x ./.github/workflows/scripts/*.sh
      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install_flutter.sh
      - name: "Run unit tests"
        run: flutter test test/

  android_integration_test:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Configure scripts "
        run: chmod +x ./.github/workflows/scripts/*.sh

      - name: "Install Flutter"
        run: ./.github/workflows/scripts/install_flutter.sh
      #      - name: "Install Tools"
      #        run: |
      #          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
      #          echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
      #          echo "$GITHUB_WORKSPACE/_flutter/.pub-cache/bin" >> $GITHUB_PATH
      #          echo "$GITHUB_WORKSPACE/_flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: "Android Integration Test"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          cores: 3
          target: google_apis
          arch: x86_64
          profile: Nexus 5X
          script: ./.github/workflows/scripts/android_integration_test.sh
