name: vosk_flutter

on: [ push ]

defaults:
  run:
    working-directory: ./example

jobs:
  android_integration_test:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Install Flutter"
        run: |
            git clone https://github.com/flutter/flutter.git --depth 1 -b stable _flutter
            echo "$GITHUB_WORKSPACE/_flutter/bin" >> $GITHUB_PATH
      - name: "Install Tools"
        run: |
            echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
            echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
            echo "$GITHUB_WORKSPACE/_flutter/.pub-cache/bin" >> $GITHUB_PATH
            echo "$GITHUB_WORKSPACE/_flutter/bin/cache/dart-sdk/bin" >> $GITHUB_PATH

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: "Configure"
        run: chmod +x ../.github/workflows/scripts/android_integration_test.sh

      - name: "Android Integration Test"
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          cores: 3
          target: google_apis
          arch: x86_64
          profile: Nexus 5X
          script: ./.github/workflows/scripts/android_integration_test.sh